import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const substack = 'https://ethic2025.substack.com/';
const assets = {
  network: 'https://images.squarespace-cdn.com/content/v1/6a79f994e82030762f1d4633/ea7898ea-7591-4a39-844b-2c4dcd77a7f9/png.png?format=1500w',
  city: 'https://images.squarespace-cdn.com/content/v1/6a79f994e82030762f1d4633/67973b83-ed20-4dd9-a77a-02e002358b9e/ChatGPT+Image+Aug+17%2C+2026%2C+03_33_40+PM.png?format=1500w'
};
const audience = [
  ['Owners & Developers','Creating demand, defining requirements, and bringing repeatable delivery models into real projects.'],
  ['Manufacturers','Building the production capacity, products, components, and supply chains required for scale.'],
  ['Technology & Platform Leaders','Developing the digital infrastructure, automation, tools, and standards that connect the system.'],
  ['Industry Experts','Bringing evidence, technical expertise, and new models into the questions practitioners are working to solve.'],
  ['Builders & Designers','Integrating design, engineering, construction, and manufacturing into more disciplined delivery systems.'],
  ['Government & Public Sector Leaders','Using procurement, policy, programs, and large-scale demand to accelerate adoption.'],
  ['Capital & Financiers','Financing projects, companies, factories, and infrastructure that allow the industry to grow.']
];
const sessions = [
  ['Why Industrialized Housing Now','From promising ideas to practical implementation: how industry, research, and policy can align to deliver housing differently.'],
  ['The Future of Demand','How predictable, programmatic demand can give industry the certainty needed to invest and build capacity.'],
  ['When Industrialized Construction Beats Site-Built','A practical conversation about economics, schedule, quality, risk, and the conditions where offsite delivery wins.'],
  ['AEC Roles Must Change for Industrialized Construction','What owners, architects, engineers, contractors, and manufacturers must change to deliver repeatable products at scale.'],
  ['What America Can Learn From Global Industrialized Construction','Policies, production systems, and market conditions that translate—and those that do not.'],
  ['AI, Robotics, and the Future of U.S. Housing Production','The systems, demand, workforce, and information layers that could expand domestic housing capacity.'],
  ['Who Should Own What in IC?','How responsibility shifts when design, manufacturing, and site delivery become more tightly connected.'],
  ['Does IC Require Full Integration?','The operating models, interfaces, and workflows that connect delivery from design through installation.'],
  ['How Can AI Become a Trusted Layer in Housing Delivery?','How secure, auditable AI can connect fragmented systems while preserving human accountability.']
];
function Header() {
  const [open, setOpen] = useState(false);
  return <header className="site-header">
    <a className="brand" href="/" aria-label="IC Summit home"><span>IC</span><span>SUMMIT</span></a>
    <button className="menu-button" onClick={() => setOpen(!open)} aria-expanded={open}><i/><i/><i/><span className="sr-only">Open menu</span></button>
    <nav className={open ? 'is-open' : ''}><a href="/">Home</a><a href="/2026-proceedings">2026 Proceedings</a><a className="button button-small" href={substack} target="_blank" rel="noreferrer">Get Updates</a></nav>
  </header>;
}
function Footer() { return <footer><div className="shell footer-grid"><div className="footer-mark">IC<br/>SUMMIT</div><div>Industrialized Construction Summit<br/><a href={substack} target="_blank" rel="noreferrer">Join the community ↗</a></div><div className="partners">ADL Ventures<br/>UT Austin<br/>ETHIC</div></div></footer>; }
function Home() { return <><Header/><main>
  <section className="hero shell"><div className="eyebrow">THE INDUSTRIALIZED CONSTRUCTION SUMMIT</div><h1>Industrialized Construction is the solution to rebuilding America.</h1><p className="lead">Industrialized construction is a faster, more affordable, and more reliable way to build. But disconnected projects and isolated innovations cannot deliver that transformation. It requires a coordinated system that connects demand, design, manufacturing, supply chains, construction, technology, capital, and policy.</p><p className="lead">IC Summit brings together the practitioners building that system. Working across disciplines, we tackle the barriers holding industrialized construction back—and unlock a better way for America to build.</p><a className="text-link" href={substack} target="_blank" rel="noreferrer">Shape how we build <span>↗</span></a></section>
  <section className="statement"><div className="shell statement-grid"><h2>Building the Conditions for Industrialized Construction to Scale</h2><p>Industrialized construction scales when the people, processes, and products across the industry begin working as a system. The IC Summit creates those conditions.</p></div></section>
  <section className="audience shell"><div className="section-kicker">WHO SHOULD ATTEND?</div><h2>For the people building the industrialized construction industry.</h2><p className="section-intro">IC Summit is built for practitioners with a direct role in how projects are planned, financed, designed, procured, manufactured, delivered, and scaled.</p><div className="audience-grid">{audience.map(([title,copy],i)=><article className="audience-card" key={title}><span className="card-number">{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="audience-close">If you are responsible for turning industrialized construction from an opportunity into a repeatable way of building, IC Summit is where your peers are doing the work.</p><a className="button" href={substack} target="_blank" rel="noreferrer">Get notified of early bird tickets</a></section>
  <section className="typologies shell"><div className="image-frame"><img src={assets.network} alt="Industrialized construction connects multiple building types through one shared system."/></div><div><div className="section-kicker">ONE SHARED IC SYSTEM</div><h2>The IC Summit is for all typologies.</h2><p>Industrialized Construction works across housing, military facilities, hotels, healthcare, education, data centers, and other repeatable projects. These markets draw on many of the same underlying capabilities. Bringing them together creates a larger opportunity for the entire community.</p><p>More predictable demand gives manufacturers and their partners greater confidence to invest in products, facilities, workforce, suppliers, and technology. More projects create opportunities to learn, improve, and repeat.</p></div></section>
  <section className="history"><div className="shell history-grid"><img src={assets.city} alt="Illustration of an industrialized city"/><p>The Industrialized Housing Summit began this community around one of the country's most urgent building challenges. As IC Summit, we're expanding the conversation to follow the people, projects, and markets building the broader industrialized construction ecosystem.</p></div></section>
  <section className="advancing shell"><div><div className="section-kicker">THE WORK CONTINUES</div><h2>Advancing the Industry</h2></div><div><p>The Summit is designed to produce more than a two-day conversation. We’re advancing the industry by preserving our learnings instead of starting over.</p><p>We publish the sessions, ideas, disagreements, and emerging solutions openly so practitioners across the industry can learn from them, challenge them, share them, and carry the work forward.</p><a className="text-link" href="/2026-proceedings">Explore the 2026 proceedings <span>→</span></a></div></section>
  <section className="community"><div className="shell community-grid"><div><div className="section-kicker">ALL YEAR</div><h2>The IC Summit community works year round.</h2></div><div><p>Follow emerging industry questions, respond to new ideas, and receive direct notifications on our programming, white papers, and upcoming events.</p><a className="button button-light" href={substack} target="_blank" rel="noreferrer">Join the discussion</a></div></div></section>
  <section className="engage shell"><div className="section-kicker">ENGAGE YEAR ROUND</div><h2>Bring the work forward.</h2><p>Attend the Summit. Join a working group. Contribute a case, data point, or question. Partner with the people moving projects forward.</p><a className="button" href={substack} target="_blank" rel="noreferrer">Subscribe to the Substack</a></section>
  </main><Footer/></>; }
function Proceedings() { return <><Header/><main><section className="proceedings-hero shell"><div className="section-kicker">IHS26 VIDEO PROCEEDINGS</div><h1>The conversations shaping the future of industrialized construction.</h1><p className="lead">At IHS26, leaders across development, manufacturing, AEC, technology, government, and capital came together to work through the questions that determine whether industrialized construction can scale.</p><p className="lead">We’re releasing those conversations, starting with demand, then moving through supply, AEC transformation, and the big questions the industry still needs to solve.</p></section><section className="proceedings-list shell">{sessions.map(([title,description],i)=><article className="session" key={title}><span>{String(i+1).padStart(2,'0')}</span><div><h2>{title}</h2><p>{description}</p><a className="text-link" href="#updates">Watch session <span>→</span></a></div></article>)}</section><section id="updates" className="community"><div className="shell community-grid"><div><div className="section-kicker">STAY INFORMED</div><h2>More proceedings are on the way.</h2></div><div><p>Subscribe to receive new sessions and the latest questions shaping industrialized construction.</p><a className="button button-light" href={substack} target="_blank" rel="noreferrer">Get updates</a></div></div></section></main><Footer/></>; }
createRoot(document.getElementById('root')).render(window.location.pathname === '/2026-proceedings' ? <Proceedings/> : <Home/>);
